### ISSUE TITLE
[Bug] progress bar duplicates

### ISSUE THREAD

**Issue by jenslys** [jenslys/nrkdl#4]
Duplicate progress bars when adding `--write-metadata` and `--write-subtitles` 

![Screenshot 2022-12-02 at 23 10 59@2x](https://user-images.githubusercontent.com/69081683/205398794-7fad85c8-0730-441d-a065-6c69863bea7a.png)

**Comment by jenslys** [comment]
@runarmod 🤨

**Comment by runarmod** [comment]
I can't seem to reproduce the bug ![bilde](https://user-images.githubusercontent.com/40912933/205405486-c447549a-affe-4770-8161-3a7349e1ab73.png)
